### ISSUE TITLE
Clippy nightly false positive

### ISSUE THREAD

**Issue by danieleades** [marshallpierce/rust-base64#188]
clippy is throwing a false positive

```
cargo +nightly clippy                                                                                                                                 101 ✘ 
    Checking base64 v0.20.0-alpha.1 (/home/dan/Code/rust/rust-base64)
error: parameter is only used in recursion
   --> src/engine/fast_portable/mod.rs:203:34
    |
203 | pub(crate) const fn decode_table(alphabet: &Alphabet) -> [u8; 256] {
    |                                  ^^^^^^^^ help: if this is intentional, prefix with an underscore: `_alphabet`
    |
note: the lint level is defined here
   --> src/lib.rs:86:5
    |
86  |     warnings
    |     ^^^^^^^^
    = note: `#[deny(clippy::only_used_in_recursion)]` implied by `#[deny(warnings)]`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#only_used_in_recursion

error: could not compile `base64` due to previous error
```

see https://github.com/rust-lang/rust-clippy/issues/8629

**Comment by hellow554** [comment]
Technically you linked the wrong issue. It should be https://github.com/rust-lang/rust-clippy/issues/8556 and I already reported that there 😅

**Comment by hellow554** [comment]
The issued is closed and should be working as intended. Can you Test it again please?

**Comment by danieleades** [comment]
i'm still seeing this issue with `rustc 1.65.0-nightly (015a824f2 2022-08-22)`

**Comment by Alexendoo** [comment]
The changes haven't reached rust nightly yet as clippy & the rust repo are synced up periodically. Should be some time this/next week

**Comment by marshallpierce** [comment]
No issues with stable or nightly clippy currently.
